In [23]:
tot_sum = open("10_test.txt") do f
    tot = 0
    topo_map = Array{Array{Int8, 1}, 1}()
    j = 0
    i = 1
    
    for l in eachline(f)
        push!(topo_map, [parse(Int, c) for c in l])
        i += 1
    end
    nb_rows = i-1
    nb_cols = length(topo_map[1])
    display(topo_map)

    # Iterate 10 times
    reachable = zeros(Int, nb_rows, nb_cols)
    for i in range(1, nb_rows)
        for j in range(1,nb_cols)
            if topo_map[i][j] == 0
                reachable[i,j] = 1
            end
        end
    end
    display(reachable)

    
    for v in range(1,9)
        for i in range(1, nb_rows)
            for j in range(1, nb_cols)
                if topo_map[i][j] == v
                    if i > 1
                        if reachable[i-1,j] > 0 && topo_map[i-1][j] == (v-1)
                            reachable[i,j] += reachable[i-1,j]
                            # println("AFound something interesting at position ", i, ", ", j)
                        end
                    end
                    if j > 1 
                        if reachable[i,j-1] > 0 && topo_map[i][j-1] == (v-1)
                            reachable[i,j] += reachable[i,j-1]
                            # println("BFound something interesting at position ", i, ", ", j)
                        end
                    end
                    if j < nb_cols 
                        if reachable[i,j+1] > 0 && topo_map[i][j+1] == (v-1)
                            reachable[i,j] += reachable[i,j+1]
                            # println("CFound something interesting at position ", i, ", ", j)
                        end
                    end
                    if i < nb_rows
                        if reachable[i+1,j] > 0 && topo_map[i+1][j] == (v-1)
                            reachable[i,j] += reachable[i+1,j]
                            # println("CFound something interesting at position ", i, ", ", j)
                        end
                    end
                end
            end
        end
        
    end

    display(reachable)
    for i in range(1, nb_rows)
        for j in range(1,nb_cols)
            if topo_map[i][j] == 9
                tot += reachable[i,j]
            end
        end
    end
    (tot)
end

8-element Vector{Vector{Int8}}:
 [8, 9, 0, 1, 0, 1, 2, 3]
 [7, 8, 1, 2, 1, 8, 7, 4]
 [8, 7, 4, 3, 0, 9, 6, 5]
 [9, 6, 5, 4, 9, 8, 7, 4]
 [4, 5, 6, 7, 8, 9, 0, 3]
 [3, 2, 0, 1, 9, 0, 1, 2]
 [0, 1, 3, 2, 9, 8, 0, 1]
 [1, 0, 4, 5, 6, 7, 3, 2]

8×8 Matrix{Int64}:
 0  0  1  0  1  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  1  0
 0  0  1  0  0  1  0  0
 1  0  0  0  0  0  1  0
 0  1  0  0  0  0  0  0

8×8 Matrix{Int64}:
  0  12   1   2   1   1  1  1
  0  12   1   5   2   5  5  1
 12  12   5   5   1  10  5  5
 12  12  10   5  17   5  5  4
  2   2  12  12  12  17  1  4
  2   2   1   1  12   1  3  4
  1   2   1   1   1   1  1  1
  2   1   1   1   1   1  1  1

81

In [36]:
tot_sum = open("10_1.txt") do f
    tot = 0
    topo_map = Array{Array{Int8, 1}, 1}()
    j = 0
    i = 1
    
    for l in eachline(f)
        push!(topo_map, [parse(Int, c) for c in l])
        i += 1
    end
    nb_rows = i-1
    nb_cols = length(topo_map[1])
    display(topo_map)

    # Iterate 10 times
    reachable = zeros(Int, nb_rows, nb_cols)
    for i in range(1, nb_rows)
        for j in range(1,nb_cols)
            if topo_map[i][j] == 9
                reachable[i,j] = 1
            end
        end
    end
    display(reachable)

    
    for v in 8:-1:0
        for i in range(1, nb_rows)
            for j in range(1, nb_cols)
                if topo_map[i][j] == v
                    if i > 1
                        if reachable[i-1,j] > 0 && topo_map[i-1][j] == (v+1)
                            reachable[i,j] += reachable[i-1,j]
                            # println("AFound something interesting at position ", i, ", ", j)
                        end
                    end
                    if j > 1 
                        if reachable[i,j-1] > 0 && topo_map[i][j-1] == (v+1)
                            reachable[i,j] += reachable[i,j-1]
                            # println("BFound something interesting at position ", i, ", ", j)
                        end
                    end
                    if j < nb_cols 
                        if reachable[i,j+1] > 0 && topo_map[i][j+1] == (v+1)
                            reachable[i,j] += reachable[i,j+1]
                            # println("CFound something interesting at position ", i, ", ", j)
                        end
                    end
                    if i < nb_rows
                        if reachable[i+1,j] > 0 && topo_map[i+1][j] == (v+1)
                            reachable[i,j] += reachable[i+1,j]
                            # println("CFound something interesting at position ", i, ", ", j)
                        end
                    end
                end
            end
        end
        
    end

    display(reachable)
    for i in range(1, nb_rows)
        for j in range(1,nb_cols)
            if topo_map[i][j] == 0
                tot += reachable[i,j]
            end
        end
    end
    (tot)
end

47-element Vector{Vector{Int8}}:
 [7, 8, 4, 3, 4, 5, 6, 5, 6, 5  …  0, 1, 6, 9, 5, 6, 7, 8, 7, 6]
 [8, 9, 1, 2, 5, 6, 7, 6, 5, 4  …  1, 6, 7, 8, 4, 7, 8, 9, 6, 5]
 [7, 4, 0, 3, 4, 3, 8, 9, 0, 1  …  0, 5, 0, 1, 3, 2, 9, 4, 5, 0]
 [6, 5, 9, 8, 5, 2, 9, 3, 4, 0  …  3, 4, 3, 2, 0, 1, 0, 3, 2, 1]
 [5, 4, 8, 7, 6, 1, 0, 2, 5, 6  …  7, 5, 8, 9, 8, 7, 6, 5, 0, 1]
 [0, 3, 1, 2, 3, 0, 0, 1, 2, 7  …  0, 6, 7, 0, 3, 4, 5, 4, 3, 2]
 [1, 2, 0, 5, 4, 3, 2, 0, 9, 8  …  1, 5, 6, 1, 2, 1, 0, 8, 9, 4]
 [2, 3, 0, 6, 5, 0, 1, 1, 2, 3  …  3, 2, 5, 4, 3, 0, 8, 7, 4, 3]
 [5, 2, 1, 7, 6, 0, 2, 0, 1, 4  …  4, 1, 6, 5, 7, 8, 9, 6, 5, 2]
 [4, 3, 9, 8, 2, 1, 7, 6, 5, 4  …  5, 0, 4, 5, 6, 3, 0, 0, 0, 1]
 [0, 4, 3, 4, 3, 9, 8, 7, 2, 3  …  6, 5, 5, 4, 3, 2, 1, 1, 0, 0]
 [1, 5, 4, 5, 8, 9, 8, 0, 1, 5  …  7, 8, 9, 3, 0, 3, 3, 2, 3, 4]
 [2, 6, 9, 6, 7, 8, 9, 8, 0, 6  …  5, 6, 7, 6, 1, 2, 8, 7, 4, 4]
 ⋮
 [7, 8, 7, 6, 5, 6, 0, 1, 2, 7  …  8, 9, 0, 3, 4, 9, 8, 7, 0, 1]
 [0, 1, 2, 5, 1, 0, 1, 2, 3, 6  …  7, 8, 1, 2, 3, 4, 5

47×47 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0  1  0  …  0  0  0  0  0  1  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  1  0  0
 0  0  0  0  0  0  0  1  0  0  0  0  0     0  0  0  0  0  0  0  0  1  0  0  0
 0  0  1  0  0  0  1  0  0  0  0  0  0     0  1  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  1  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  1  0
 0  0  0  0  0  0  0  0  0  0  0  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  1  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0  0  1  0     0  0  0  0  1  0  0  0  0  0  0  0
 0  0  1  0  0  0  1  0  0  0  0  0  0     

47×47 Matrix{Int64}:
 2  1   0   6  6  4  2  4  0  0  1  …  0  3   6  0  1  1  5  5  3  1  1  1
 1  1  10  10  2  2  2  2  2  2  2     3  3   3  1  1  1  5  2  2  1  1  2
 1  1  10   4  4  4  2  1  2  2  2     6  9  12  1  2  2  5  5  1  1  1  1
 1  1   1   1  2  4  1  1  1  2  1     6  1   2  2  2  2  5  5  5  1  1  1
 1  2   1   2  2  4  4  1  1  1  1     6  1   1  1  1  1  1  1  1  1  2  2
 2  2   3   3  3  4  1  1  0  1  1  …  1  1   1  1  1  2  1  1  1  2  2  2
 2  2   3   1  3  3  3  2  1  1  1     1  1   1  2  1  2  2  2  2  1  1  0
 0  0   1   1  2  3  3  1  1  1  1     2  0   1  1  1  1  1  2  1  2  2  2
 0  1   1   1  1  3  0  2  1  0  1     2  1   1  1  0  0  1  1  1  2  2  2
 0  1   1   1  3  3  1  2  2  2  2     0  0   1  1  1  1  1  0  1  1  2  2
 1  1   8   3  3  1  1  1  2  2  1  …  1  1   1  1  0  1  1  1  1  1  1  2
 1  1   4   3  1  1  2  2  2  1  1     1  2   1  1  1  1  1  0  0  1  1  0
 1  1   1   3  3  2  1  1  3  1  1     1  3   1  1  1  1  1  1  1  1  1  0
 ⋮  

1045

In [26]:
using DataStructures

In [34]:
tot_sum = open("10_1.txt") do f
    tot = 0
    topo_map = Array{Array{Int8, 1}, 1}()
    j = 0
    i = 1
    
    for l in eachline(f)
        push!(topo_map, [parse(Int, c) for c in l])
        i += 1
    end
    nb_rows = i-1
    nb_cols = length(topo_map[1])
    display(topo_map)

    # Iterate 10 times
    # reachable = Array{Array{Set, 1}, 1}()
    reachable = [Set{Tuple{Int,Int}}() for i=1:nb_rows, j=1:nb_cols] 
    for i in range(1, nb_rows)
        for j in range(1,nb_cols)
            if topo_map[i][j] == 9
                push!(reachable[i,j], ((i,j)))
            end
        end
    end
    display(reachable)

    
    for v in 8:-1:0
        println("v = ", v)
        for i in range(1, nb_rows)
            for j in range(1, nb_cols)
                if topo_map[i][j] == v
                    if i > 1
                        if length(reachable[i-1,j]) > 0 && topo_map[i-1][j] == (v+1)
                            reachable[i,j] = union(reachable[i,j], reachable[i-1,j])
                            # println("AFound something interesting at position ", i, ", ", j)
                        end
                    end
                    if j > 1 
                        if length(reachable[i,j-1]) > 0 && topo_map[i][j-1] == (v+1)
                            reachable[i,j] = union(reachable[i,j], reachable[i,j-1])
                            # println("BFound something interesting at position ", i, ", ", j)
                        end
                    end
                    if j < nb_cols 
                        if length(reachable[i,j+1]) > 0 && topo_map[i][j+1] == (v+1)
                            reachable[i,j] = union(reachable[i,j], reachable[i,j+1])
                            # println("CFound something interesting at position ", i, ", ", j)
                        end
                    end
                    if i < nb_rows
                        if length(reachable[i+1,j]) > 0 && topo_map[i+1][j] == (v+1)
                            reachable[i,j] = union(reachable[i,j], reachable[i+1,j])
                            # println("CFound something interesting at position ", i, ", ", j)
                        end
                    end
                end
            end
        end
        
    end

    display(reachable)
    for i in range(1, nb_rows)
        for j in range(1,nb_cols)
            if topo_map[i][j] == 0
                tot += length(reachable[i,j])
            end
        end
    end
    (tot)
end

47-element Vector{Vector{Int8}}:
 [7, 8, 4, 3, 4, 5, 6, 5, 6, 5  …  0, 1, 6, 9, 5, 6, 7, 8, 7, 6]
 [8, 9, 1, 2, 5, 6, 7, 6, 5, 4  …  1, 6, 7, 8, 4, 7, 8, 9, 6, 5]
 [7, 4, 0, 3, 4, 3, 8, 9, 0, 1  …  0, 5, 0, 1, 3, 2, 9, 4, 5, 0]
 [6, 5, 9, 8, 5, 2, 9, 3, 4, 0  …  3, 4, 3, 2, 0, 1, 0, 3, 2, 1]
 [5, 4, 8, 7, 6, 1, 0, 2, 5, 6  …  7, 5, 8, 9, 8, 7, 6, 5, 0, 1]
 [0, 3, 1, 2, 3, 0, 0, 1, 2, 7  …  0, 6, 7, 0, 3, 4, 5, 4, 3, 2]
 [1, 2, 0, 5, 4, 3, 2, 0, 9, 8  …  1, 5, 6, 1, 2, 1, 0, 8, 9, 4]
 [2, 3, 0, 6, 5, 0, 1, 1, 2, 3  …  3, 2, 5, 4, 3, 0, 8, 7, 4, 3]
 [5, 2, 1, 7, 6, 0, 2, 0, 1, 4  …  4, 1, 6, 5, 7, 8, 9, 6, 5, 2]
 [4, 3, 9, 8, 2, 1, 7, 6, 5, 4  …  5, 0, 4, 5, 6, 3, 0, 0, 0, 1]
 [0, 4, 3, 4, 3, 9, 8, 7, 2, 3  …  6, 5, 5, 4, 3, 2, 1, 1, 0, 0]
 [1, 5, 4, 5, 8, 9, 8, 0, 1, 5  …  7, 8, 9, 3, 0, 3, 3, 2, 3, 4]
 [2, 6, 9, 6, 7, 8, 9, 8, 0, 6  …  5, 6, 7, 6, 1, 2, 8, 7, 4, 4]
 ⋮
 [7, 8, 7, 6, 5, 6, 0, 1, 2, 7  …  8, 9, 0, 3, 4, 9, 8, 7, 0, 1]
 [0, 1, 2, 5, 1, 0, 1, 2, 3, 6  …  7, 8, 1, 2, 3, 4, 5

47×47 Matrix{Set{Tuple{Int64, Int64}}}:
 Set()  Set()          Set()           …  Set()           Set()
 Set()  Set([(2, 2)])  Set()              Set()           Set()
 Set()  Set()          Set()              Set()           Set()
 Set()  Set()          Set([(4, 3)])      Set()           Set()
 Set()  Set()          Set()              Set()           Set()
 Set()  Set()          Set()           …  Set()           Set()
 Set()  Set()          Set()              Set([(7, 46)])  Set()
 Set()  Set()          Set()              Set()           Set()
 Set()  Set()          Set()              Set()           Set()
 Set()  Set()          Set([(10, 3)])     Set()           Set()
 Set()  Set()          Set()           …  Set()           Set()
 Set()  Set()          Set()              Set()           Set()
 Set()  Set()          Set([(13, 3)])     Set()           Set()
 ⋮                                     ⋱  ⋮               
 Set()  Set()          Set()           …  Set()           Set()
 Set(

v = 8
v = 7
v = 6
v = 5
v = 4
v = 3
v = 2
v = 1
v = 0


47×47 Matrix{Set{Tuple{Int64, Int64}}}:
 Set([(2, 2)])            Set([(2, 2)])            …  Set([(2, 45)])
 Set([(2, 2)])            Set([(2, 2)])               Set([(2, 45)])
 Set([(2, 2)])            Set([(2, 2)])               Set([(2, 45)])
 Set([(2, 2)])            Set([(2, 2)])               Set([(2, 45)])
 Set([(2, 2)])            Set([(2, 2)])               Set([(5, 41)])
 Set([(2, 2)])            Set([(2, 2)])            …  Set([(5, 41)])
 Set([(2, 2)])            Set([(2, 2)])               Set()
 Set()                    Set()                       Set([(9, 44), (7, 46)])
 Set()                    Set([(13, 3)])              Set([(9, 44), (7, 46)])
 Set()                    Set([(13, 3)])              Set([(9, 44), (7, 46)])
 Set([(16, 1)])           Set([(13, 3)])           …  Set([(9, 44), (7, 46)])
 Set([(16, 1)])           Set([(13, 3)])              Set()
 Set([(16, 1)])           Set([(13, 3)])              Set()
 ⋮                                                 ⋱  

512